# analyzing the following curve
# "324.a1"	324	1	[]	0	[0, 0, 0, -189, -999]	[[-8, 1]]
# y^2 = x^3 -189x - 999
# E(Q) = Z = <(-8,1)>

from ec import *
from sympy.ntheory import isprime


def check(line):
    linedata = line.split('\t')
    filename = str(linedata[0])

    writefile = open("neversurjdata/"+filename+"pointdicts123v2.txt", "w")
    writefile.write(line)
    writefile.write('\n\n')
    writefile.write('p prime of good reduction, N = #E(F_p), isCyclic, index of E(Q) in E(F_p), order of image of E(Q) \n\n')
    # primes < 1000 aka first 168 primes
    primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97,
              101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199,
              211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293,
              307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397
            #   401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499,
            #   503, 509, 521, 523, 
            #   541, 
            #   547, 557, 563, 569, 
            #   571, 
            #   577, 587, 593, 599,
            #   601, 
            #   607, 
            #   613, 617, 619, 
            #   631, 
            #   641, 643, 647, 653, 659, 661, 673, 677, 683, 691,
            #   701, 709, 719, 727, 733, 739, 743, 
            #   751, 
            #   757, 761, 769, 773, 787, 797,
            #   809, 811, 821, 823, 827, 829, 839, 853, 857, 
            #   859, 
            #   863, 877, 881, 883, 887,
            #   907, 911, 919, 929, 
            #   937
            #   , 941, 947, 953, 967, 971, 977, 983, 991, 997
            ]    
    
    surjprimes = []
    notsurjprimes = []
    primeprimes = []
    print(line)

    linedata = line.split('\t')
    conductor = int(linedata[1])
    E = eval(linedata[5])
    gens = parseGens(linedata[6])
    # tors = eval(linedata[3])

    # E = [0, 0, 1, -1, 0]
    # conductor = 37
    # gens = [[0,0]]

    # indexdict = {}

    for p in primes:
        print("Analyzing p = ",p, end= "\r")

        orderdict = {}
        if conductor % p != 0:

            # find orders of all elements (to inefficiently determine group structure)
            pts = getFpPoints(E,p)
            N = len(pts)
            notcyclic = True
            for pt in pts:
                ptModP = pointModP(pt,p)
                P = ptModP

                # check if pt^{i} = O
                for i in range(1, N):
                    if P == "infinity":
                        orderdict[pt] = i
                        break

                    if i == N-1: # if P has N-1 nontrivial powers, then it is necessarily a generator for all E(F_p)
                        notcyclic = False
                        orderdict[pt] = N


                    # compute P^{i+1}
                    P = ellMultFp(E, P, ptModP,p)

            # redundant coding for now
            # gather index of image of E(Q)
#### v3

                # v3: gather reduced MW gens, then compute subgroup H generated by the gens
                # gather gens mod p
                gensModP = []
                for gen in gens:
                    gensModP.append(pointModP(gen,p))
                
                # initialize H
                H = {}
                H['infinity'] = 1

                # iterate through gens, construct H = <gensModP>
                for genModP in gensModP:
                    
                    # gather points in H at the beginning of this step
                    priorH = list(H.keys())

                    # if the gen is not already in the subgroup H, append cosets (gen+H)^i to H
                    if not genModP in priorH:
                        P = genModP
                        for i in range(1,N):
                            # take powers until in the coset H
                            if P in priorH:
                                break

                            # otherwise, add P+H
                            else:
                                for Q in priorH:
                                    prod = ellMultFp(E, P, Q, p)
                                    pts[prod] += 1
                                    H[prod] = 1

                            P = ellMultFp(E, P, genModP,p)

#### end v3

            # for gen in gens:
            #     genModP = pointModP(gen,p)
            #     P = genModP

            #     for i in range(1,N):
            #         if P == "infinity":
            #             break
            #         pts[P] += 1
            #         P = ellMultFp(E, P, genModP,p)

                # if every Fp point has been hit, then all values are > 0


            if not (0 in pts.values()):
                imagesize = N
                
            else:
                imagesize = 0
                for key in pts.keys():
                    if pts[key] > 0:
                        imagesize+= 1
            
            # indexdict[p] = N // imagesize
            
            writefile.write(str(p) + ', ' + str(N) + ', ' + str(not(notcyclic)) + ', ' + str(N/imagesize) + ', ' + str(imagesize) + '\n')
            writefile.write(str(orderdict))
            writefile.write('\n \n')

            


    # surjcount = len(surjprimes)
    # notsurjcount = len(notsurjprimes)
    # primecount = len(primeprimes)
    # total = len(primes)


    # print("\n")
    
    # print("surj:", surjcount)
    # print("notsurj:", notsurjcount)#, notsurjprimes)
    # print("prime order:", primecount)#,primeprimes)
    # print("surj percentage:", surjcount/total)
    # print("prime order percentage:", primecount/surjcount)
    # print(indexdict)
    print("\n")
    
    # return(indexdict)
    writefile.close()


# check('"189.b1"	189	1	[]	0	[0, 0, 1, -3834, -91375]	[[-143/2, -3/2]]')
# check('"254.b1"	254	1	[]	0	[1, 0, 0, -24432, -1471934]	[[-36131/20, 361313/20]]')
check('"324.a1"	324	1	[]	0	[0, 0, 0, -189, -999]	[[-8, 1]]')
# check('"324.a2"\t324\t1\t[]\t0\t[0, 0, 0, -9, 9]\t[[-3,3],[3,3]]')

# check('"378.b3"	378	1	[]	0	[1, -1, 0, 849, -25939]	[[62, 481]]')
# check('"402.b1"	402	1	[]	0	[1, 0, 1, -10255, -438718]	[[8799/5, 764372/5]]')
# check('"430.c1"	430	1	[]	0	[1, 0, 0, -5626, -162894]	[[771/2, 18699/2]]')
# check('"460.c2"	460	1	[]	0	[0, 1, 0, 414, -13915]	[[613/3, 15625/3]]')
# check('"486.d1"	486	1	[]	0	[1, -1, 1, -1109, -13931]	[[-19, 8]]')
# check('"540.a1"	540	1	[]	0	[0, 0, 0, -513, -4563]	[[28, 55]]')
# check('"540.b2"	540	1	[]	0	[0, 0, 0, 1512, 33588]	[[-11, 125]]')
# check('"540.d2"	540	1	[]	0	[0, 0, 0, 3, 1]	[[0, 1]]')
# check('"564.b1"	564	1	[]	0	[0, 1, 0, -517, -4681]	[[-14, 3]]')
# check('"574.g1"	574	1	[]	0	[1, -1, 1, -9611313, -11466507927]	[[-402671/15, 3021062/15]]')
# check('"612.a1"	612	1	[]	0	[0, 0, 0, -4104, -101196]	[[93, 567]]')
